version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:15
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    working_directory: ~/repo

jobs:
  install:
    executor: node-executor

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  linter:
    executor: node-executor

    steps:
      - checkout
      - run: git reset --soft origin/dev
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: git config --global user.email "test@kf.com"
      - run: git config --global user.name "Kids First Bot"
      - run: npm run pretest

  # tests:
  #   executor: node-executor
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           - v1-dependencies-{{ checksum "package.json" }}
  #           - v1-dependencies-
  #     - run: npm run test -- --maxWorkers=2
  #     - store_artifacts:
  #         path: coverage
  #     - save_cache:
  #         paths:
  #           - node_modules
  #         key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2.1

  tests:
    jobs:
      - install
      # - tests:
      #     requires:
      #       - install
      - linter:
          requires:
            - install
