name: Tests

on:
  pull_request:
    branches: [dev]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14.17'
      - name: use cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/ya.lock') }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
